#!/bin/sh
set -e
package_name=imagemagick-hide
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/display-im6.q16.desktop"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/display-im6.q16.desktop"
;;
esac
exit 0
