#!/bin/sh
set -e
package_name=imagemagick-hide
mkdir -p "/usr/share/dpkgdivert/imagemagick-hide"
case "$1" in
  install)
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/imagemagick-hide/usrshareapplicationsdisplay-im6.q16.desktop" --rename "/usr/share/applications/display-im6.q16.desktop"
    ;;
  upgrade)
if [ "$(dpkg-divert --list "/usr/share/applications/display-im6.q16.desktop")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/imagemagick-hide/usrshareapplicationsdisplay-im6.q16.desktop" --rename "/usr/share/applications/display-im6.q16.desktop"
fi
;;
esac
exit 0
